// Lints a decision-first review/comparison post (see SPEC.md). Usage: node tasks/review-format/lint.js posts-new/post-<slug>.html
const fs = require('fs'), path = require('path');
const file = process.argv[2];
const s = fs.readFileSync(file, 'utf8');
const live = new Set(fs.readFileSync(path.join(__dirname, 'live-posts.txt'), 'utf8').split(/\r?\n/).filter(Boolean).map(u => u.replace(/\/?$/, '/')));
const body = s.replace(/<script[\s\S]*?<\/script>/g, '');
const txt = body.replace(/<[^>]+>/g, ' ').replace(/&[a-z#0-9]+;/g, ' ');
const errs = [], warns = [];
if (/—/.test(s)) errs.push('em dash found');
const banned = ['delve', 'navigate', 'game-changer', 'moreover', 'furthermore', "in today's fast-paced world", 'in conclusion', 'unleash', 'leverage', 'seamlessly', 'dive deep', 'robust', 'cutting-edge', 'revolutionary', 'transformative', 'harness', 'embark', 'journey'];
banned.forEach(w => { if (new RegExp('\\b' + w, 'i').test(txt)) errs.push('banned word: ' + w); });
if (/<h1[\s>]/i.test(s)) errs.push('contains <h1>');
if (/\]\(https?:/.test(body)) errs.push('markdown link');
if (/\[(PERSONAL EXPERIENCE|UNIQUE INSIGHT|ORIGINAL DATA|IMAGE:|CHART:|CITATION:)/.test(s)) errs.push('editorial marker left');
['foco-review-meta', 'foco-tldr', 'foco-cmp2', 'foco-key-takeaways'].forEach(c => { if (!s.includes(c)) errs.push('missing .' + c); });
if (!/<h2>FAQ<\/h2>/i.test(s)) errs.push('missing <h2>FAQ</h2>');
if (!/<h2>How did we compare/i.test(s)) errs.push('missing "How did we compare" section');
if (/table of contents/i.test(s)) errs.push('in-body table of contents');
if (/FOCO is free|free version of FOCO|FOCO free tier|FOCO'?s free plan/i.test(txt)) errs.push('claims FOCO is free');
if (/we tested (tiimo|structured|inflow|aligned|amazing marvin|marvin)/i.test(txt)) errs.push('claims hands-on test of a competitor');
const ps = [...body.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/g)].map(m => m[1].replace(/<[^>]+>/g, '').replace(/\b(e\.g|i\.e|vs|approx|Dr|St)\./gi, 'x').replace(/\$?\d+\.\d+/g, 'N'));
ps.forEach(p => { if ((p.match(/[.!?](\s|$)/g) || []).length > 2) errs.push('paragraph >2 sentences: ' + p.trim().slice(0, 70)); });
const links = [...body.matchAll(/<a\s[^>]*href="([^"]+)"[^>]*>/g)];
const internal = links.filter(m => /tryfoco\.com/.test(m[1])), external = links.filter(m => !/tryfoco\.com/.test(m[1]));
internal.forEach(m => { const u = m[1].split('#')[0].replace(/\/?$/, '/'); if (u !== 'https://www.tryfoco.com/' && !live.has(u)) errs.push('internal link not live: ' + m[1]); });
if (internal.length < 4) errs.push('fewer than 4 internal links (' + internal.length + ')');
if (external.length < 3) errs.push('fewer than 3 external links (' + external.length + ')');
const authority = /nimh\.nih\.gov|chadd\.org|russellbarkley\.org|\.gov\/|\.edu\/|pubmed|ncbi\.nlm/;
external.forEach(m => { const tag = m[0]; const isAuth = authority.test(m[1]); if (!isAuth && !/nofollow/.test(tag)) errs.push('competitor link without nofollow: ' + m[1]); if (!/target="_blank"/.test(tag) || !/noopener/.test(tag)) warns.push('external link missing target/noopener: ' + m[1]); });
if (!external.some(m => authority.test(m[1]))) errs.push('no authority citation (NIMH / CHADD / Barkley / .gov / .edu)');
const ld = s.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
if (!ld) errs.push('missing JSON-LD'); else { try { const j = JSON.parse(ld[1]); const types = JSON.stringify(j); if (!/FAQPage/.test(types)) errs.push('JSON-LD without FAQPage'); if (!/SoftwareApplication/.test(types)) errs.push('JSON-LD without SoftwareApplication'); if (/aggregateRating|reviewRating/.test(types)) errs.push('JSON-LD has rating values'); } catch (e) { errs.push('JSON-LD invalid: ' + e.message); } }
if (/&&/.test(s)) errs.push('"&&" breaks on WordPress');
const words = txt.split(/\s+/).filter(Boolean).length;
if (words < 1100 || words > 1900) warns.push('word count ' + words + ' (target 1200-1700)');
console.log(file, '| words', words, '| internal', internal.length, '| external', external.length);
warns.forEach(w => console.log('  warn:', w));
errs.forEach(e => console.log('  ERROR:', e));
console.log(errs.length ? `FAIL (${errs.length})` : 'PASS');
process.exit(errs.length ? 1 : 0);
